core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

oc_plateform:
    resource: "@OCPlateformBundle/Resources/config/routing.yml"
    prefix:   /platform

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
