oc_plateform_home:
    path: /{page}
    defaults: { _controller: OCPlateformBundle:Advert:index, page: 1}
    requirements:
      page: \d+

oc_plateform_view:
   path: /advert/{id}
   defaults: { _controller: OCPlateformBundle:Advert:view }
   requirements:
     id: \d+

oc_plateform_add:
   path: /add
   defaults: { _controller: OCPlateformBundle:Advert:view }

oc_platform_edit:
    path:      /edit/{id}
    defaults:
      _controller: OCPlateformBundle:Advert:edit
    requirements:
      id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:
      _controller: OCPlateformBundle:Advert:delete
    requirements:
      id: \d+


oc_plateform_view_slug:
    path: /{year}/{slug}.{_format}
    defaults:
      _controller: OCPlateformBundle:Advert:viewSlug
      _format: xml
      _locale: fr
    requirements:
      year: \d{4}
      _format: html|xml
      _locale: fr|en

oc_plateform_hello_world:
    path: /hello-world
    defaults: { _controller: OCPlateformBundle:Advert:add }

